module.exports = {
  // AC Business Media
  dmnews: {
    name: 'DM News',
    domain: 'dmnews.com',
    project: 'AC Business Media',
    accountKey: 'acbm',
    groupKey: 'dmn',
    tenantKey: 'acbm_dmn',
    replicaSet: 'caprica',
  },
  greenindustrypros: {
    name: 'Green Industry Pros',
    domain: 'greenindustrypros.com',
    project: 'AC Business Media',
    accountKey: 'acbm',
    groupKey: 'gip',
    tenantKey: 'acbm_gip',
    replicaSet: 'caprica',
  },
  forconstructionpros: {
    name: 'For Construction Pros',
    domain: 'forconstructionpros.com',
    project: 'AC Business Media',
    accountKey: 'acbm',
    groupKey: 'fcp',
    tenantKey: 'acbm_fcp',
    replicaSet: 'caprica',
  },
  foodlogistics: {
    name: 'Food Logistics',
    domain: 'foodlogistics.com',
    project: 'AC Business Media',
    accountKey: 'acbm',
    groupKey: 'fl',
    tenantKey: 'acbm_fl',
    replicaSet: 'caprica',
  },
  oemoffhighway: {
    name: 'OEM Off Highway',
    domain: 'oemoffhighway.com',
    project: 'AC Business Media',
    accountKey: 'acbm',
    groupKey: 'ooh',
    tenantKey: 'acbm_ooh',
    replicaSet: 'caprica',
  },
  sdcexec: {
    name: 'Supply & Demand Chain Executive',
    domain: 'sdcexec.com',
    project: 'AC Business Media',
    accountKey: 'acbm',
    groupKey: 'sdce',
    tenantKey: 'acbm_sdce',
    replicaSet: 'caprica',
  },

  // AS3
  baseplatform: {
    name: 'Base Platform',
    domain: 'baseplatform.io',
    project: 'AS3',
    accountKey: 'as3',
    groupKey: 'baseplatform',
    tenantKey: 'as3_baseplatform',
    replicaSet: 'picon',
  },
  clarity: {
    name: 'Clarity',
    domain: 'clarity.endeavorb2b.com',
    project: 'AS3',
    accountKey: 'as3',
    groupKey: 'clarity',
    tenantKey: 'as3_clarity',
    replicaSet: 'picon',
  },

  // Bizbash Media, LLC
  bizbash: {
    name: 'BizBash',
    domain: 'bizbash.com',
    project: 'BizBash',
    accountKey: 'bizbash',
    groupKey: 'bzb',
    tenantKey: 'bizbash_bzb',
    replicaSet: 'caprica',
  },

  // Carey Media
  thepitchkc: {
    name: 'The Pitch',
    domain: 'thepitchkc.com',
    project: 'Carey Media',
    accountKey: 'careymedia',
    groupKey: 'kcp',
    tenantKey: 'scomm_kcp',
    replicaSet: 'caprica',
  },

  // Cygnus Business Media
  aviationpros: {
    name: 'Aviation Pros',
    domain: 'aviationpros.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'cavc',
    tenantKey: 'cygnus_cavc',
    replicaSet: 'picon'
  },
  cpapracticeadvisor: {
    name: 'CPA Practice Advisor',
    domain: 'cpapracticeadvisor.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'cpa',
    tenantKey: 'cygnus_cpa',
    replicaSet: 'picon'
  },
  firehouse: {
    name: 'Firehouse',
    domain: 'firehouse.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'fhc',
    tenantKey: 'cygnus_fhc',
    replicaSet: 'picon'
  },
  locksmithledger: {
    name: 'Locksmith Ledger',
    domain: 'locksmithledger.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'll',
    tenantKey: 'cygnus_ll',
    replicaSet: 'picon'
  },
  masstransitmag: {
    name: 'Mass Transit Magazine',
    domain: 'masstransitmag.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'mass',
    tenantKey: 'cygnus_mass',
    replicaSet: 'picon'
  },
  officer: {
    name: 'Officer',
    domain: 'officer.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'ofcr',
    tenantKey: 'cygnus_ofcr',
    replicaSet: 'picon',
  },
  securityinfowatch: {
    name: 'Security Info Watch',
    domain: 'securityinfowatch.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'siw',
    tenantKey: 'cygnus_siw',
    replicaSet: 'picon'
  },
  vendingmarketwatch: {
    name: 'Vending Market Watch',
    domain: 'vendingmarketwatch.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'vmw',
    tenantKey: 'cygnus_vmw',
    replicaSet: 'picon'
  },
  vehicleservicepros: {
    name: 'Vehicle Service Pros',
    domain: 'vehicleservicepros.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'vspc',
    tenantKey: 'cygnus_vspc',
    replicaSet: 'picon'
  },

  // Endeavor Business Media
  evaluationengineering: {
    name: 'Evaluation Engineering',
    domain: 'evaluationengineering.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'ee',
    tenantKey: 'ebm_ee',
    replicaSet: 'picon',
  },
  flowcontrolnetwork: {
    name: 'Flow Control Network',
    domain: 'flowcontrolnetwork.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'fcn',
    tenantKey: 'ebm_fcn',
    replicaSet: 'picon',
  },
  forresternetwork: {
    name: 'Forrester Network',
    domain: 'forresternetwork.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'frn',
    tenantKey: 'ebm_frn',
    replicaSet: 'picon',
  },
  hcinnovationgroup: {
    name: 'Healthcare Innovation',
    domain: 'hcinnovationgroup.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'hci',
    tenantKey: 'ebm_hci',
    replicaSet: 'picon',
  },
  hpnonline: {
    name: 'Healthcare Purchasing News',
    domain: 'hpnonline.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'hpn',
    tenantKey: 'ebm_hpn',
    replicaSet: 'picon',
  },
  'mlo-online': {
    name: 'Medical Laboratory Observer',
    domain: 'mlo-online.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'mlo',
    tenantKey: 'ebm_mlo',
    replicaSet: 'picon',
  },
  processingmagazine: {
    name: 'Processing Magazine',
    domain: 'processingmagazine.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'pm',
    tenantKey: 'ebm_pm',
    replicaSet: 'picon',
  },
  plasticsmachinerymagazine: {
    name: 'Plastics Machinery Magazine',
    domain: 'plasticsmachinerymagazine.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'pmm',
    tenantKey: 'ebm_pmm',
    replicaSet: 'picon',
  },
  watertechonline: {
    name: 'Water Technology',
    domain: 'watertechonline.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'wto',
    tenantKey: 'ebm_wto',
    replicaSet: 'picon',
  },

  // Euclid Media Group
  citybeat: {
    name: 'City Beat',
    domain: 'citybeat.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'cb',
    tenantKey: 'scomm_cb',
    replicaSet: 'caprica',
  },
  cltampa: {
    name: 'Creative Loafing: Tampa',
    domain: 'cltampa.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'cltampa',
    tenantKey: 'scomm_cltampa',
    replicaSet: 'caprica',
  },

  // FW Publishing
  nfocusnashville: {
    name: 'nFocus Nashville',
    domain: 'nfocusnashville.com',
    project: 'FW Publishing',
    accountKey: 'fwp',
    groupKey: 'nfn',
    tenantKey: 'scomm_nfn',
    replicaSet: 'caprica',
  },
  nashvillescene: {
    name: 'Nashville Scene',
    domain: 'nashvillescene.com',
    project: 'FW Publishing',
    accountKey: 'fwp',
    groupKey: 'nvs',
    tenantKey: 'scomm_nvs',
    replicaSet: 'caprica',
  },
  nashvillepost: {
    name: 'Nashville Post',
    domain: 'nashvillepost.com',
    project: 'FW Publishing',
    accountKey: 'fwp',
    groupKey: 'nvp',
    tenantKey: 'scomm_nvp',
    replicaSet: 'caprica',
  },

  // Industrial Media Group
  cannabisequipmentnews: {
    name: 'Cannabis Equipment News',
    domain: 'cannabisequipmentnews.com',
    project: 'Industrial Media Group',
    accountKey: 'indm',
    groupKey: 'cen',
    tenantKey: 'indm_cen',
    replicaSet: 'caprica',
  },
  designdevelopmenttoday: {
    name: 'Design & Development Today',
    domain: 'designdevelopmenttoday.com',
    project: 'Industrial Media Group',
    accountKey: 'indm',
    groupKey: 'ddt',
    tenantKey: 'indm_ddt',
    replicaSet: 'caprica',
  },
  ien: {
    name: 'Industrial Equipment News',
    domain: 'ien.com',
    project: 'Industrial Media Group',
    accountKey: 'indm',
    groupKey: 'ien',
    tenantKey: 'indm_ien',
    replicaSet: 'caprica',
  },
  madeinamericaseries: {
    name: 'Made In America Series',
    domain: 'madeinamericaseries.com',
    project: 'Industrial Media Group',
    accountKey: 'indm',
    groupKey: 'mia',
    tenantKey: 'indm_mia',
    replicaSet: 'aerilon'
  },

  // PennWell Corporation
  bioopticsworld: {
    name: 'Bio Optics World',
    domain: 'bioopticsworld.com',
    logo: 'http://base.imgix.net/files/base/pennwell/bow/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'bow',
    tenantKey: 'ebm_bow',
    replicaSet: 'aerilon'
  },
  broadbandtechreport: {
    name: 'Broadband Technology Report',
    domain: 'broadbandtechreport.com',
    logo: 'http://base.imgix.net/files/base/pennwell/btr/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'btr',
    tenantKey: 'ebm_btr',
    replicaSet: 'aerilon'
  },
  cablinginstall: {
    name: 'Cabling Installation & Maintenance',
    domain: 'cablinginstall.com',
    logo: 'http://base.imgix.net/files/base/pennwell/cim/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'cim',
    tenantKey: 'ebm_cim',
    replicaSet: 'aerilon'
  },
  dentalacademyofce: {
    name: 'Dental Academy of Continuing Education',
    domain: 'dentalacademyofce.com',
    logo: 'http://base.imgix.net/files/base/pennwell/dace/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'dace',
    tenantKey: 'ebm_dace',
    replicaSet: 'aerilon'
  },
  dentaleconomics: {
    name: 'Dental Economics',
    domain: 'dentaleconomics.com',
    logo: 'http://base.imgix.net/files/base/pennwell/de/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'de',
    tenantKey: 'ebm_de',
    replicaSet: 'aerilon',
    primaryNavItems: [
      { href: '/macro-op-ed', label: 'Macro/Op-Ed' },
      { href: '/practice', label: 'Practice' },
      { href: '/science-tech', label: 'Science & Tech' },
      { href: '/money', label: 'Money' },
      { href: '/dental-office-design', label: 'Dental Office Design' },
    ],
    secondaryNavItems: [
      { href: '/subscribe', label: 'Subscribe'},
      { href: 'https://www.dentalacademyofce.com', label: 'Earn CE' },
      { href: '/white-papers', label: 'White Papers' },
      { href: '/videos', label: 'Videos' },
      { href: '/job-listings', label: 'Job Listings' },
      { href: 'https://www.dentistryiq.com/products/free-samples', label: 'Free Samples' },
    ],
    ads: {
      units: {
        BS: {
          path: '/21687441225/DE/DE_BS',
          size: [[970, 250], [970, 90], [728, 90], [300, 50]],
        },
        MR: {
          path: '/21687441225/DE/DE_MR',
          size: [300, 250],
        },
        HP: {
          path: '/21687441225/DE/DE_HP',
          size: [300, 600],
        },
      },
    },
  },
  dentistryiq: {
    name: 'DentistryIQ',
    domain: 'dentistryiq.com',
    logo: 'http://base.imgix.net/files/base/pennwell/diq/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'diq',
    tenantKey: 'ebm_diq',
    replicaSet: 'aerilon',
    primaryNavItems: [
      { href: '/practice-management', label: 'Practice Management' },
      { href: '/assistants', label: 'Assistants' },
      { href: '/clinical', label: 'Clinical' },
      { href: '/front-office', label: 'Front Office' },
      { href: '/dental-hygiene', label: 'Dental Hygiene' },
      { href: '/industry', label: 'Industry' },
      { href: '/products', label: 'Products' },
      { href: '/continuing-education', label: 'Continuing Education' },
    ],
    secondaryNavItems: [
      { href: '/subscribe', label: 'Subscribe'},
      { href: '/products/free-samples', label: 'Free Samples' },
      { href: '/blogs', label: 'Blogs' },
      { href: '/videos', label: 'Videos' },
      { href: '/webcasts', label: 'Webcasts' },
    ],
    ads: {
      units: {
        BS: {
          path: '/21687441225/DIQ/DIQ_BS',
          size: [[970, 250], [970, 90], [728, 90], [300, 50]],
        },
        MR: {
          path: '/21687441225/DIQ/DIQ_MR',
          size: [300, 250],
        },
        HP: {
          path: '/21687441225/DIQ/DIQ_HP',
          size: [300, 600],
        },
      },
    },
  },
  'intelligent-aerospace': {
    name: 'Intelligent Aerospace',
    domain: 'intelligent-aerospace.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ias/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ias',
    tenantKey: 'ebm_ias',
    replicaSet: 'aerilon',
  },
  'industrial-lasers': {
    name: 'Industrial Laser Solutions',
    domain: 'industrial-lasers.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ils/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ils',
    tenantKey: 'ebm_ils',
    replicaSet: 'aerilon',
  },
  ledsmagazine: {
    name: 'LEDs Magazine',
    domain: 'ledsmagazine.com',
    logo: 'http://base.imgix.net/files/base/pennwell/leds/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'leds',
    tenantKey: 'ebm_leds',
    replicaSet: 'aerilon',
  },
  laserfocusworld: {
    name: 'Laser Focus World',
    domain: 'laserfocusworld.com',
    logo: 'http://base.imgix.net/files/base/pennwell/lfw/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'lfw',
    tenantKey: 'ebm_lfw',
    replicaSet: 'aerilon',
  },
  lightwaveonline: {
    name: 'Lightwave',
    domain: 'lightwaveonline.com',
    logo: 'http://base.imgix.net/files/base/pennwell/lw/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'lw',
    tenantKey: 'ebm_lw',
    replicaSet: 'aerilon',
  },
  militaryaerospace: {
    name: 'Military & Aerospace Electronics',
    domain: 'militaryaerospace.com',
    logo: 'http://base.imgix.net/files/base/pennwell/mae/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'mae',
    tenantKey: 'ebm_mae',
    replicaSet: 'aerilon',
  },
  'offshore-mag': {
    name: 'Offshore Magazine',
    domain: 'offshore-mag.com',
    logo: 'http://base.imgix.net/files/base/pennwell/os/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'os',
    tenantKey: 'ebm_os',
    replicaSet: 'aerilon',
  },
  ogj: {
    name: 'Oil & Gas Journal',
    domain: 'ogj.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ogj/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ogj',
    tenantKey: 'ebm_ogj',
    replicaSet: 'aerilon',
  },
  rdhmag: {
    name: 'Registered Dental Hygienist',
    domain: 'rdhmag.com',
    logo: 'http://base.imgix.net/files/base/pennwell/rdh/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'rdh',
    tenantKey: 'ebm_rdh',
    replicaSet: 'aerilon',
  },
  perioimplantadvisory: {
    name: 'Perio-Implant Advisory',
    domain: 'perioimplantadvisory.com',
    logo: 'http://base.imgix.net/files/base/pennwell/pia/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'pia',
    tenantKey: 'ebm_pia',
    replicaSet: 'aerilon',
    primaryNav: [
      { href: '/clinical-tips-from-the-editor', label: 'Clinical Tips from the Editor' },
      { href: '/complications', label: 'Complications' },
      { href: '/dental-practice-management', label: 'Dental Practice Management' },
      { href: '/hygiene', label: 'Hygiene' },
      { href: '/oral-systemic', label: 'Oral-Systemic' },
      { href: '/restorative', label: 'Restorative' },
      { href: '/surgical', label: 'Surgical' },
      { href: '/team-treatment-planning', label: 'Team Treatment Planning' },
    ],
    secondaryNavItems: [
      { href: '/subscribe', label: 'Subscribe'},
      { href: '/editors-picks', label: 'Editor\'s Picks' },
      { href: '/videos', label: 'Videos' },
      { href: '/job-listings', label: 'Job Listings' },
    ],
    ads: {
      units: {
        BS: {
          path: '/21687441225/PIA/PIA_BS',
          size: [[970, 250], [970, 90], [728, 90], [300, 50]],
        },
        MR: {
          path: '/21687441225/PIA/PIA_MR',
          size: [300, 250],
        },
        HP: {
          path: '/21687441225/PIA/PIA_HP',
          size: [300, 600],
        },
      },
    },
  },
  'strategies-u': {
    name: 'Strategies Unlimited',
    domain: 'strategies-u.com',
    logo: 'http://base.imgix.net/files/base/pennwell/su/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'su',
    tenantKey: 'ebm_su',
    replicaSet: 'aerilon',
  },
  utilityproducts: {
    name: 'Utility Products',
    domain: 'utilityproducts.com',
    logo: 'http://base.imgix.net/files/base/pennwell/up/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'up',
    tenantKey: 'ebm_up',
    replicaSet: 'aerilon',
    primaryNavItems: [
      { href: '/transmission-distribution', label: 'Transmission & Distribution' },
      { href: '/vehicles-accessories', label: 'Vehicles & Accessories' },
      { href: '/tools-supplies', label: 'Tools & Supplies' },
      { href: '/safety', label: 'Safety' },
      { href: '/line-construction-maintenance', label: 'Line Construction & Maintenance' },
      { href: '/test-measurement', label: 'Test & Measurement' },
    ],
    secondaryNavItems: [
      { href: '/subscribe', label: 'Subscribe'},
      { href: '/videos', label: 'Videos' },
      { href: '/white-papers', label: 'White Papers' },
      { href: '/events', label: 'Events' },
    ],
    ads: {
      units: {
        BS: {
          path: '/21687441225/UP/UP_BS',
          size: [[970, 250], [970, 90], [728, 90], [300, 50]],
        },
        MR: {
          path: '/21687441225/UP/UP_MR',
          size: [300, 250],
        },
        HP: {
          path: '/21687441225/UP/UP_HP',
          size: [300, 600],
        },
      },
    },
  },
  'vision-systems': {
    name: 'Vision Systems Design',
    domain: 'vision-systems.com',
    logo: 'http://base.imgix.net/files/base/pennwell/vsd/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'vsd',
    tenantKey: 'ebm_vsd',
    replicaSet: 'aerilon',
  },
  waterworld: {
    name: 'WaterWorld',
    domain: 'waterworld.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ww/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ww',
    tenantKey: 'ebm_ww',
    replicaSet: 'aerilon',
    primaryNav: [
      { href: '/municipal', label: 'Municipal' },
      { href: '/industrial', label: 'Industrial' },
      { href: '/international', label: 'International' },
    ],
    secondaryNavItems: [
      { href: '/subscribe', label: 'Subscribe'},
      { href: '/global-thought-leaders', label: 'Global Thought Leaders' },
      { href: '/whitepapers', label: 'Whitepapers' },
      { href: '/webcasts', label: 'Webcasts' },
      { href: '/events', label: 'Events' },
      { href: '/video', label: 'Video' },
    ],
    ads: {
      units: {
        BS: {
          path: '/21687441225/WW/WW_BS',
          size: [[970, 250], [970, 90], [728, 90], [300, 50]],
        },
        MR: {
          path: '/21687441225/WW/WW_MR',
          size: [300, 250],
        },
        HP: {
          path: '/21687441225/WW/WW_HP',
          size: [300, 600],
        },
      },
    },
  },

  // Washington City Paper
  washingtoncitypaper: {
    name: 'Washington City Paper',
    domain: 'washingtoncitypaper.com',
    project: 'Washington City Paper',
    accountKey: 'wcp',
    groupKey: 'wcp',
    tenantKey: 'scomm_wcp',
    replicaSet: 'caprica',
  },

  // What They Think
  printingnews: {
    name: 'Printing News',
    domain: 'printingnews.com',
    project: 'What They Think',
    accountKey: 'wtt',
    groupKey: 'pn',
    tenantKey: 'cygnus_mprc',
    replicaSet: 'caprica',
  },
};
